<?php

declare(strict_types=1);

namespace AlexisPPLIN\SendcloudV3\Endpoints;

use AlexisPPLIN\SendcloudV3\Client;
use AlexisPPLIN\SendcloudV3\Exceptions\SendcloudRequestException;
use AlexisPPLIN\SendcloudV3\Models\Order\Order;
use InvalidArgumentException;
use Throwable;

class Orders extends Client
{
    /**
     * Retrieve an order
     * Find a specific order by its order ID.
     * 
     * @see https://sendcloud.dev/api/v3/orders/retrieve-an-order
     *
     * @throws SendcloudRequestException
     */
    public function getOrder(int $id): Order
    {
        try {
            $response = $this->client->get('/orders/' . $id);

            SendcloudRequestException::fromResponse($response);

            $body = $response->getBody()->getContents();

            return Order::fromData(json_decode($body, true)['data']);
        } catch (Throwable $throwable) {
            SendcloudRequestException::fromException($throwable);
        }
    }

    /**
     * Retrieve a list of orders
     * Get a list of orders filtered by integration, order number, order ID, order status, creation date, and update date. You can also optionally sort the results and pass a cursor value.
     * 
     * @see https://sendcloud.dev/api/v3/orders/retrieve-a-list-of-orders
     * 
     * @param ?array<int> $integration Filter orders by one or more integration IDs.
     * @param $order_number Filter orders by a specific order number. The filtering is case insensitive.
     * @param $order_id Filter orders by a specific order id. The filtering is case insensitive.
     * @param $status Filter orders based on their status=. The filtering is case insensitive.
     * @param $order_created_at Find orders that were created on a specific date.
     * @param $order_created_at_min Find orders that were created at or after a specific date.
     * @param $order_created_at_max Find orders that were created at or after a specific date.
     * @param $order_updated_at Find orders that were created at or after a specific date.
     * @param $order_updated_at_min Find orders that were created at or after a specific date.
     * @param $order_updated_at_max Find orders that were created at or after a specific date.
     * @param $sort Sort the orders in the response by using one or more of the following values:
     *              - integration: Sort by the integration ID of the retrieved orders; to sort in descending order, use -integration
     *              - order_number: Sort by the order number of the retrieved orders; to sort in descending order, use -order_number.
     *              - order_created_at: Sort by the date of an order creation of the retrieved orders; to sort in descending order, use -order_created_at
     *              - order_updated_at: Sort by the date of an order update of the retrieved orders; to sort in descending order, use -order_updated_at
     *              - pk: Sort by the ID (autogenerated internal ID) of the retrieved orders; to sort in descending order, use -pk
     * 
     *              Additional information about this query: 
     *              - Any valid combination of the above values is supported, e.g. sort=integration,-order_created_at.
     *              - In case of conflicting sort values, e.g. /?sort=integration,-integration, the conflicting value will be ignored.
     *              - If the sort query parameter is not set, the sorting of the retrieved orders will default to -pk.
     *              - If an unsupported sort value is provided, the results will be sorted by the default (-pk).
     *              Example:
     *              "-order_number"
     * @param $page_size The maximum number of results to be returned per page
     * @param $cursor The cursor query string is used as the pivot value to filter results. If no value is provided, the first page of results will be returned. To get this value, you must encode the offset, reverse and position into a base64 string.
     *                There are 3 possible parameters to encode:
     *                - o: Offset
     *                - r: Reverse
     *                - p: Position
     *                For example, r=1&p=300 encoded as a base64 string would be cj0xJnA9MzAw. The query string would then be cursor=cj0xJnA9MzAw.
     *                
     *                Example:
     *                "cj0xJnA9MzAw"
     * @return array<Order>
     * 
     * @throws SendcloudRequestException
     */
    public function getOrders(
        ?array $integration = null,
        ?string $order_number = null,
        ?string $order_id = null,
        ?string $status = null,
        ?string $order_created_at = null,
        ?string $order_created_at_min = null,
        ?string $order_created_at_max = null,
        ?string $order_updated_at = null,
        ?string $order_updated_at_min = null,
        ?string $order_updated_at_max = null,
        ?string $sort = null,
        ?int $page_size = null,
        ?string $cursor = null,
    ) : array {
        // Build query parameters

        $query = [];

        if (isset($integration) && !empty($integration)) {
            $query['integration'] = $integration;
        }

        if (isset($order_number)) {
            $query['order_number'] = $order_number;
        }

        if (isset($order_id)) {
            $query['order_id'] = $order_id;
        }

        if (isset($status)) {
            $query['status'] = $status;
        }

        if (isset($order_created_at)) {
            $query['order_created_at'] = $order_created_at;
        }

        if (isset($order_created_at_min)) {
            $query['order_created_at_min'] = $order_created_at_min;
        }

        if (isset($order_created_at_max)) {
            $query['order_created_at_max'] = $order_created_at_max;
        }

        if (isset($order_updated_at)) {
            $query['order_updated_at'] = $order_updated_at;
        }

        if (isset($order_updated_at_min)) {
            $query['order_updated_at_min'] = $order_updated_at_min;
        }

        if (isset($order_updated_at_max)) {
            $query['order_updated_at_max'] = $order_updated_at_max;
        }

        if (isset($sort)) {
            $query['sort'] = $sort;
        }

        if (isset($page_size)) {
            $query['page_size'] = $page_size;
        }

        if (isset($cursor)) {
            $query['cursor'] = $cursor;
        }

        $uri = '/orders?' . http_build_query($query);
        
        try {
            // Send request

            $response = $this->client->get($uri);
            SendcloudRequestException::fromResponse($response);

            // Parse response

            $body = $response->getBody()->getContents();
            $response = json_decode($body, true);

            $orders = [];
            foreach ($response['data'] as $order) {
                $orders[] = Order::fromData($order);
            }

            return $orders;
        } catch (Throwable $throwable) {
           SendcloudRequestException::fromException($throwable);
        }
    }

    /**
     * Update an order
     * Partially update some fields of an order.
     *
     * @see https://sendcloud.dev/api/v3/orders/update-an-order
     * 
     * @return int Sendcloud order ID
     * @throws SendcloudRequestException
     * @throws InvalidArgumentException
     */
    public function updateOrder(
        Order $order
    ): int {
        if (!isset($order->id)) {
            throw new InvalidArgumentException('Order id is null');
        }

        try {
            $body = json_encode($order);
            $response = $this->client->patch('/orders/' . $order->id, [], $body);

            SendcloudRequestException::fromResponse($response);

            $body = $response->getBody()->getContents();
            $json = json_decode($body, true);

            return (int) $json['data']['id'];
        } catch (Throwable $throwable) {
            SendcloudRequestException::fromException($throwable);
        }
    }

    /**
     * Create/Update orders in batch
     * Use this endpoint to insert orders into a Sendcloud API integration.
     * 
     * @see https://sendcloud.dev/api/v3/orders/create-update-orders-in-batch
     * 
     * @param array<Order> $orders
     * @return array<int> Sendcloud orders IDs
     * 
     * @throws SendcloudRequestException
     */
    public function createOrder(
        array $orders
    ) : array {
        try {
            $body = json_encode($orders);
            $response = $this->client->post('/orders', [], $body);

            SendcloudRequestException::fromResponse($response);

            $body = $response->getBody()->getContents();
            $json = json_decode($body, true);

            $ids = array_column($json['data'], 'id');
            $ids = array_map('intval', $ids);

            return $ids;
        } catch (Throwable $throwable) {
            SendcloudRequestException::fromException($throwable);
        }
    }

    /**
     * Delete an order
     * Delete an order by its unique id.
     * 
     * @see https://sendcloud.dev/api/v3/orders/delete-an-order
     * 
     * @throws SendcloudRequestException
     */
    public function deleteOrder(
        int $id
    ): void {
        try {
            $response = $this->client->post('/orders/' . $id);

            SendcloudRequestException::fromResponse($response);
        } catch (Throwable $throwable) {
            SendcloudRequestException::fromException($throwable);
        }
    }
}
