<?php

namespace AlexisPPLIN\SendcloudV3\Models\Order;

use AlexisPPLIN\SendcloudV3\Models\Address;
use AlexisPPLIN\SendcloudV3\Models\Customer\CustomerDetails;
use AlexisPPLIN\SendcloudV3\Models\ModelInterface;
use AlexisPPLIN\SendcloudV3\Models\PaymentDetails;
use AlexisPPLIN\SendcloudV3\Models\ServicePoint\ServicePoint;
use AlexisPPLIN\SendcloudV3\Utils\DateUtils;
use AlexisPPLIN\SendcloudV3\Utils\JsonUtils;
use DateTimeImmutable;

class Order implements ModelInterface
{
    /**
     * @param $order_id External order ID assigned by shop system
     * @param $order_number Unique order number generated manually or by shop system
     * @param $order_details Node for general order information
     * @param $payment_details Node for everything about payments and money
     * @param $id Autogenerated Sendcloud's internal ID
     * @param $created_at The date when an order was created at Sendcloud in ISO 8601
     * @param $modified_at The date when an order was last modified at Sendcloud in ISO 8601
     * @param $customs_details Customs information required for international shipments.
     * @param $customer_details Node for an information about customer.
     * @param $shipping_details Shipping information
     * @param $service_point_details Node for service point information. The service point information can be retrieved from the Service points API {@see https://sendcloud.dev/api/v2/service-points}
     */
    public function __construct(
        public readonly string $order_id,
        public readonly string $order_number,
        public readonly OrderDetails $order_details,
        public readonly PaymentDetails $payment_details,
        public readonly ?string $id = null,
        public readonly ?DateTimeImmutable $created_at = null,
        public readonly ?DateTimeImmutable $modified_at = null,
        public readonly ?CustomsDetails $customs_details = null,
        public readonly ?CustomerDetails $customer_details = null,
        public readonly ?Address $billing_address = null,
        public readonly ?Address $shipping_address = null,
        public readonly ?ShippingDetails $shipping_details = null,
        public readonly ?ServicePoint $service_point_details = null
    ) {

    }

    public static function fromData(array $data) : self
    {
        return new self(
            order_id:               (string) $data['order_id'],
            order_number:           (string) $data['order_number'],
            order_details:          OrderDetails::fromData($data['order_details']),
            payment_details:        PaymentDetails::fromData($data['payment_details']),
            id:                     isset($data['id'])                      ? (string) $data['id'] : null,
            created_at:             isset($data['created_at'])              ? DateUtils::iso8601ToDateTime($data['created_at'])      : null,
            modified_at:            isset($data['modified_at'])             ? DateUtils::iso8601ToDateTime($data['modified_at'])     : null,
            customs_details:        isset($data['customs_details'])         ? CustomsDetails::fromData($data['customs_details'])        : null,
            customer_details:       isset($data['customer_details'])        ? CustomerDetails::fromData($data['customer_details'])      : null,
            billing_address:        isset($data['billing_address'])         ? Address::fromData($data['billing_address'])               : null,
            shipping_address:       isset($data['shipping_address'])        ? Address::fromData($data['shipping_address'])              : null,
            shipping_details:       isset($data['shipping_details'])        ? ShippingDetails::fromData($data['shipping_details'])      : null,
            service_point_details:  isset($data['service_point_details'])   ? ServicePoint::fromData($data['service_point_details'])    : null,
        );
    }

    public function jsonSerialize() : array
    {
        $json = [
            'order_id' => $this->order_id,
            'order_number' => $this->order_number,
            'order_details' => $this->order_details,
            'payment_details' => $this->payment_details
        ];

        JsonUtils::addIfNotNull($json, 'id', $this->id);

        if (isset($this->created_at)) {
            $json['created_at'] = DateUtils::dateTimeToIso8601($this->created_at);
        }

        if (isset($this->modified_at)) {
            $json['modified_at'] = DateUtils::dateTimeToIso8601($this->modified_at);
        }

        JsonUtils::addIfNotNull($json, 'customs_details', $this->customs_details);
        JsonUtils::addIfNotNull($json, 'customer_details', $this->customer_details);
        JsonUtils::addIfNotNull($json, 'billing_address', $this->billing_address);
        JsonUtils::addIfNotNull($json, 'shipping_address', $this->shipping_address);
        JsonUtils::addIfNotNull($json, 'shipping_details', $this->shipping_details);
        JsonUtils::addIfNotNull($json, 'service_point_details', $this->service_point_details);

        return ['data' => $json];
    }
}